# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='passward',
            field=models.CharField(default='rootroot', max_length=25),
        ),
        migrations.AddField(
            model_name='vm',
            name='username',
            field=models.CharField(default='root', max_length=25),
        ),
        migrations.AlterField(
            model_name='vm',
            name='host',
            field=models.CharField(default='redhat66', max_length=25),
        ),
        migrations.AlterField(
            model_name='vm',
            name='ip',
            field=models.CharField(default='127.0.0.1', max_length=45),
        ),
    ]
